<a href="https://colab.research.google.com/github/ashivin10/rinex_majorProject/blob/main/rinex__proje_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [130]:
import pandas as pd
df=pd.read_csv("/content/ETH.csv")
df

Date         Open         High          Low        Close  \
0    2020-06-16   229.762299   236.394302   228.426147   234.416168   
1    2020-06-17   234.492371   235.954056   229.341644   233.028275   
2    2020-06-18   232.898697   234.570648   228.951431   232.101166   
3    2020-06-19   231.954971   232.154114   226.795181   227.138290   
4    2020-06-20   226.976364   231.449020   226.640625   229.274261   
..          ...          ...          ...          ...          ...   
725  2022-06-11  1665.217896  1679.314209  1507.038940  1529.663452   
726  2022-06-12  1530.189697  1539.705078  1436.183960  1445.216553   
727  2022-06-13  1443.835449  1448.738037  1181.948242  1204.582764   
728  2022-06-14  1204.555298  1252.471802  1094.701904  1211.662842   
729  2022-06-15  1204.709473  1219.879272  1025.767456  1091.898193   

       Adj Close       Volume  
0     234.416168   7965648016  
1     233.028275   7701391592  
2     232.101166   6713800872  
3     227.138290   6946372590  
4     229.274261   6252830566  
..           ...          ...  
725  1529.663452  21127089064  
726  1445.216553  23465074882  
727  1204.582764  45162788786  
728  1211.662842  33327826525  
729  1091.898193  30485518336  

[730 rows x 7 columns]

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       730 non-null    object 
 1   Open       730 non-null    float64
 2   High       730 non-null    float64
 3   Low        730 non-null    float64
 4   Close      730 non-null    float64
 5   Adj Close  730 non-null    float64
 6   Volume     730 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 40.0+ KB


In [132]:
df.shape


(730, 7)

In [133]:
df=df.drop(labels=["Date"],axis=1)


In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Open       730 non-null    float64
 1   High       730 non-null    float64
 2   Low        730 non-null    float64
 3   Close      730 non-null    float64
 4   Adj Close  730 non-null    float64
 5   Volume     730 non-null    int64  
dtypes: float64(5), int64(1)
memory usage: 34.3 KB


In [135]:
#seperating input and output
x=df.iloc[:,0:2].values
y=df.iloc[:,2].values


In [142]:
#splits x and y to 75% and 25%
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(x,y,random_state=0)
xt=xte

In [143]:

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(xtr,ytr)


LinearRegression()

In [144]:
ypred=model.predict(xte)
ypred

array([ 692.82294767,  622.43508464,  212.41737488,  217.55805638,
       2027.48390913, 2702.75689368, 2038.81709221, 1861.80279527,
       2876.25275711,  226.18294339,  288.81749251, 2356.68271642,
        370.2391166 ,  459.99607765,  600.45760231,  573.68840704,
       2496.83578082, 2864.81082456, 2075.20284064,  417.42535111,
       2782.37336381, 1370.67367463, 2960.72274725,  570.00768328,
       2236.82557051, 2655.53657046,  993.05303701, 1760.2567008 ,
       2518.90998328, 4468.6884233 ,  228.94216309, 1734.47303004,
       2982.04316396,  559.23260838, 2627.80929269, 1932.98595657,
       2981.48384351, 3789.25600936,  386.44692029, 3709.93118094,
       3274.83152938,  218.60697645, 1828.21874364, 2928.92119853,
       3165.58928727, 2591.75584199, 2282.40143245, 1793.05654092,
       1732.78965961,  324.65508986, 4461.10941579, 3372.57660849,
       3508.41751851, 3898.17744794, 1181.09156668, 4040.15386325,
       3893.99849247, 3305.27973659, 3213.24206229, 2101.43913

In [145]:
yte

array([ 692.149414,  625.014465,  224.815186,  232.10997 , 2083.803711,
       2755.908447, 2119.865723, 1907.020508, 2676.407471,  238.232376,
        300.267822, 2326.869629,  391.041504,  471.63147 ,  617.4021  ,
        588.346375, 2308.914795, 2786.253174, 2117.590088,  381.1297  ,
       2845.397705, 1181.948242, 2962.4104  ,  559.671387, 2298.026855,
       2630.120361,  912.305359, 1770.612061, 2573.655273, 4144.334961,
        232.807739, 1789.914185, 3087.490723,  552.469238, 2583.995117,
       1922.577881, 3075.911377, 3918.837891,  399.608368, 3703.399902,
       3365.817627,  229.341644, 1845.119995, 2900.926025, 3278.670898,
       2566.193115, 2312.301514, 1848.206299, 1722.050781,  332.165009,
       4580.990234, 3335.376709, 3590.275146, 4033.513916, 1174.38855 ,
       3785.848633, 3638.12207 , 3442.000244, 3247.91748 , 2049.962646,
       3283.44873 , 2449.353516, 2587.748291, 2868.938965, 4255.455078,
       1830.531494, 1749.606323, 3142.00708 , 4718.039063, 3016.

In [148]:
model.predict([df.iloc[1,0:2].values])


array([218.60697645])

In [149]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

a=3444
b=4555
m=[[730.358704,  737.952881]]
print(ls)
model.predict(m)


[[0. 0.]]


array([692.82294767])

In [152]:
import joblib
joblib.dump(model,"eth_vol")

['eth_vol']

In [153]:
!pip install streamlit --quiet

In [157]:
%%writefile app.py
import streamlit as st
import joblib
import numpy as np
t_mod=joblib.load("eth_vol")
st.title("ETHERIUM COIN LOW PRICE PREDICTION!!")
st.write("""This is basically a website to predict the lowest value that an etheerium coin can reach based on ..\nOpen market cost and higest price recorded in a day*""")
ip1=st.number_input("MARKET OPEN PRICE")
ip2=st.number_input("HIGEST RECORDED VALUE")
ls1=np.append(ip1,ip2)
op=t_mod.predict([ls1])
if st.button("PREDICT"):
  st.title(op)


Overwriting app.py


In [160]:
!streamlit run app.py & npx localtunnel --port 8501

2022-07-01 18:27:46.545 INFO    numexpr.utils: NumExpr defaulting to 2 threads.
npx: installed 22 in 2.765s
your url is: https://blue-carrots-decide-34-72-126-97.loca.lt

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:8501
  External URL: http://34.72.126.97:8501

  Stopping...
^C
