<a href="https://colab.research.google.com/github/ashivin10/rinex_majorProject/blob/main/rinex__proje_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
df=pd.read_csv("/content/ETH.csv")
df

Date         Open         High          Low        Close  \
0    2020-06-16   229.762299   236.394302   228.426147   234.416168   
1    2020-06-17   234.492371   235.954056   229.341644   233.028275   
2    2020-06-18   232.898697   234.570648   228.951431   232.101166   
3    2020-06-19   231.954971   232.154114   226.795181   227.138290   
4    2020-06-20   226.976364   231.449020   226.640625   229.274261   
..          ...          ...          ...          ...          ...   
725  2022-06-11  1665.217896  1679.314209  1507.038940  1529.663452   
726  2022-06-12  1530.189697  1539.705078  1436.183960  1445.216553   
727  2022-06-13  1443.835449  1448.738037  1181.948242  1204.582764   
728  2022-06-14  1204.555298  1252.471802  1094.701904  1211.662842   
729  2022-06-15  1204.709473  1219.879272  1025.767456  1091.898193   

       Adj Close       Volume  
0     234.416168   7965648016  
1     233.028275   7701391592  
2     232.101166   6713800872  
3     227.138290   6946372590  
4     229.274261   6252830566  
..           ...          ...  
725  1529.663452  21127089064  
726  1445.216553  23465074882  
727  1204.582764  45162788786  
728  1211.662842  33327826525  
729  1091.898193  30485518336  

[730 rows x 7 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       730 non-null    object 
 1   Open       730 non-null    float64
 2   High       730 non-null    float64
 3   Low        730 non-null    float64
 4   Close      730 non-null    float64
 5   Adj Close  730 non-null    float64
 6   Volume     730 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 40.0+ KB


In [4]:
df.shape


(730, 7)

In [10]:
df=df.drop(labels=["Date"],axis=1)


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Open       730 non-null    float64
 1   High       730 non-null    float64
 2   Low        730 non-null    float64
 3   Close      730 non-null    float64
 4   Adj Close  730 non-null    float64
 5   Volume     730 non-null    int64  
dtypes: float64(5), int64(1)
memory usage: 34.3 KB


In [39]:
#seperating input and output
x=df.iloc[:,0:2].values
y=df.iloc[:,2].values


In [40]:
#splits x and y to 75% and 25%
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(x,y,random_state=0)
xtr

array([[3209.030518, 3346.526367],
       [3382.657227, 3437.935791],
       [4523.981934, 4640.921875],
       ...,
       [2555.297607, 2639.943115],
       [4064.746338, 4126.001465],
       [2729.994141, 2838.704346]])

In [41]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
sc=MinMaxScaler()
xtr=sc.fit_transform(xtr)
xte=sc.fit_transform(xte)
model=LinearRegression()
model.fit(xtr,ytr)

LinearRegression()

In [42]:
ypred=model.predict(xte)
ypred

array([ 685.20760694,  615.6730889 ,  210.71506337,  215.79061629,
       2003.52237764, 2670.72015519, 2014.64428288, 1839.99526156,
       2841.95742234,  224.31217288,  286.19711996, 2328.57455573,
        366.604806  ,  455.32795785,  594.01798411,  567.57851343,
       2467.16965008, 2830.42325965, 2050.70711572,  413.21103936,
       2749.03226001, 1354.69044984, 2925.32259808,  563.89342511,
       2210.3225958 , 2623.71487584,  982.10191594, 1739.51713528,
       2489.15435077, 4415.17835945,  227.04214249, 1714.06499039,
       2946.33610254,  553.25489262, 2596.59569014, 1910.06970696,
       2945.87008807, 3743.68901384,  382.65788068, 3666.06423053,
       3235.69631091,  216.82820771, 1806.59560916, 2894.08185108,
       3127.57255398, 2560.69857003, 2255.35654004, 1772.07405555,
       1712.36775481,  321.61149394, 4407.30295717, 3331.88708277,
       3466.52001882, 3851.31989253, 1167.50660374, 3991.6388023 ,
       3846.99287147, 3265.57644927, 3174.57237167, 2076.65754

In [48]:
yte

array([ 692.149414,  625.014465,  224.815186,  232.10997 , 2083.803711,
       2755.908447, 2119.865723, 1907.020508, 2676.407471,  238.232376,
        300.267822, 2326.869629,  391.041504,  471.63147 ,  617.4021  ,
        588.346375, 2308.914795, 2786.253174, 2117.590088,  381.1297  ,
       2845.397705, 1181.948242, 2962.4104  ,  559.671387, 2298.026855,
       2630.120361,  912.305359, 1770.612061, 2573.655273, 4144.334961,
        232.807739, 1789.914185, 3087.490723,  552.469238, 2583.995117,
       1922.577881, 3075.911377, 3918.837891,  399.608368, 3703.399902,
       3365.817627,  229.341644, 1845.119995, 2900.926025, 3278.670898,
       2566.193115, 2312.301514, 1848.206299, 1722.050781,  332.165009,
       4580.990234, 3335.376709, 3590.275146, 4033.513916, 1174.38855 ,
       3785.848633, 3638.12207 , 3442.000244, 3247.91748 , 2049.962646,
       3283.44873 , 2449.353516, 2587.748291, 2868.938965, 4255.455078,
       1830.531494, 1749.606323, 3142.00708 , 4718.039063, 3016.

In [53]:
import numpy as np
a=229
b=254
ls=np.array([])
ls=np.append(a,b)
print(ls)
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
ls=sc.fit_transform([ls])
model.predict(ls)


[229 254]


array([209.23079346])

In [19]:
import joblib
joblib.dump(model,"eth_vol")

['eth_vol']

In [58]:
!pip install streamlit --quiet

In [62]:
%%writefile app.py
import streamlit as st
import joblib
import numpy as np
model=joblib.load("eth_vol")
st.title("ETHERIUM COIN LOW PRICE PREDICTION!!")
st.write("""This is basically a website to predict the lowest value that an etheerium coin can reach based on ..\nOpen market cost and higest price recorded in a day*""")
ip1=st.number_input("MARKET OPEN PRICE")
ip2=st.number_input("HIGEST RECORDED VALUE")
ls=np.append(ip1,ip2)
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
ls=sc.fit_transform([ls])
op=model.predict(ls)
if st.button("PREDICT"):
  st.title(op)


Overwriting app.py


In [64]:
!streamlit run app.py & npx localtunnel --port 8501

2022-07-01 15:39:16.986 INFO    numexpr.utils: NumExpr defaulting to 2 threads.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:8501
  External URL: http://34.72.126.97:8501

npx: installed 22 in 2.962s
your url is: https://itchy-melons-dig-34-72-126-97.loca.lt
  Stopping...
^C
